import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import '@fortawesome/fontawesome-free/css/all.min.css';
import { ThemeProvider } from './contexts/ThemeContext';
import { AuthProvider } from "./hooks/useAuth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MindHarmony",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider>
      <AuthProvider>
          {children}
         </AuthProvider>
        </ThemeProvider>
        </body>
    </html>
  );
}
